---
- hosts: trumporate
  roles:
    - role: install_packages
    - role: provision
    - role: systemd
    - role: nginx
    # - role: deploy  # enable this after you have to update the server code
  